### ISSUE TITLE
NSInternalInconsistencyException with Cocoapods use_frameworks 

### ISSUE THREAD

**Issue by johncosch** [venmo/VENCalculatorInputView#25]
After building pods as frameworks with the "use_frameworks!" expression, I was getting this error:
````
NSInternalInconsistencyException', reason: 'Could not load NIB in bundle:' with name 'VENCalculatorInputView'
````
 I found that by changing the ```` [NSBundle mainBundle]```` to ````[NSBundle bundleForClass: [VENCalculatorInputView class]```` in VENCalculatorInputView.m I was able to fix the issue for people looking to use this in swift projects. I have not yet looked into how this would affect projects not using "use_frameworks!".

**Comment by ayanonagon** [comment]
Thank you for filing this issue! Fixed and just pushed out v1.5.1. :octocat:
